DATABASE_HOST = "127.0.0.1"
DATABASE_USER = 'root'
DATABASE_PASSWORD = '1026933660'
DATABASE_DB = 'JrSkyline'


SECRET_KEY = 'JrSkyline_key'
SESSION_TYPE = 'filesystem'

DATABASE_PORT = '3306'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8mb4'.format(DATABASE_USER, DATABASE_PASSWORD, DATABASE_HOST, DATABASE_PORT, DATABASE_DB)
SQLALCHEMY_DATABASE_URI = DB_URI
